// Mock bills data

export const bills = [
  {
    id: "ca-sb1",
    bill_id: 1001,
    number: "SB 1",
    title: "California Environmental Quality Act: housing and land use",
    state: "California",
    state_id: "ca",
    session_id: 1,
    status: "Passed",
    status_date: "2023-10-10",
    last_action: "Signed by Governor",
    last_action_date: "2023-10-10",
    description:
      "This bill would make various changes to the California Environmental Quality Act (CEQA) to facilitate the development of housing. It would exempt certain housing projects from CEQA review, streamline the CEQA process for housing projects, and limit the grounds upon which a court could invalidate a housing project's approval under CEQA.",
    sponsors: [{ id: "ca-sen-wiener", name: "Senator Scott Wiener", party: "Democratic", district: "11" }],
    history: [
      { date: "2022-12-05", action: "Introduced" },
      { date: "2023-01-12", action: "Referred to Committee on Environmental Quality" },
      { date: "2023-03-15", action: "Passed Committee (5-2)" },
      { date: "2023-04-20", action: "Passed Senate (28-12)" },
      { date: "2023-05-18", action: "Referred to Assembly Committee on Natural Resources" },
      { date: "2023-06-22", action: "Passed Committee (7-3)" },
      { date: "2023-07-15", action: "Passed Assembly (54-19)" },
      { date: "2023-07-20", action: "Returned to Senate" },
      { date: "2023-08-01", action: "Senate concurred in Assembly amendments (27-13)" },
      { date: "2023-08-10", action: "Enrolled and presented to Governor" },
      { date: "2023-10-10", action: "Signed by Governor. Chapter 310, Statutes of 2023." },
    ],
    committees: [
      "Senate Committee on Environmental Quality",
      "Senate Committee on Housing",
      "Assembly Committee on Natural Resources",
      "Assembly Committee on Housing and Community Development",
    ],
    full_text:
      'SECTION 1. The Legislature finds and declares all of the following:\n(a) California is experiencing a housing supply crisis, with housing demand far outstripping supply.\n(b) The California Environmental Quality Act (Division 13 (commencing with Section 21000) of the Public Resources Code) (CEQA) can be misused to impede the development of housing, including affordable housing.\n(c) It is the intent of the Legislature to streamline the CEQA process for housing projects while maintaining environmental protections.\n\nSECTION 2. Section 21080.XX is added to the Public Resources Code, to read:\n21080.XX. (a) This division does not apply to a housing development project that meets all of the following requirements:\n(1) The project is located on an infill site.\n(2) The project is located in an urbanized area.\n(3) The project consists of at least 50 percent residential use.\n(4) The project includes at least 10 percent affordable housing units.\n(b) For purposes of this section, the following definitions apply:\n(1) "Affordable housing unit" means a unit that is made available at an affordable rent, as defined in Section 50053 of the Health and Safety Code, to a household earning no more than 80 percent of the area median income.\n(2) "Infill site" means a site that meets the criteria specified in Section 21061.3.\n(3) "Urbanized area" means an area that meets the criteria specified in Section 21071.',
  },
  {
    id: "ny-a1",
    bill_id: 1002,
    number: "A 1",
    title: "Relates to establishing the New York health act and to making appropriations therefor",
    state: "New York",
    state_id: "ny",
    session_id: 2,
    status: "In Committee",
    status_date: "2023-01-04",
    last_action: "Referred to Health Committee",
    last_action_date: "2023-01-04",
    description:
      "This bill would establish the New York Health Act, a comprehensive system of access to health insurance for New York state residents. It would provide universal, comprehensive health care coverage without deductibles, co-pays, restricted provider networks, or out-of-network charges.",
    sponsors: [
      { id: "ny-asm-gottfried", name: "Assemblymember Richard Gottfried", party: "Democratic", district: "75" },
      { id: "ny-asm-gonzalez", name: "Assemblymember Jessica González-Rojas", party: "Democratic", district: "34" },
    ],
    history: [
      { date: "2023-01-04", action: "Introduced" },
      { date: "2023-01-04", action: "Referred to Health Committee" },
    ],
    committees: ["Assembly Committee on Health", "Assembly Committee on Ways and Means"],
    full_text:
      'SECTION 1. Short title. This act shall be known and may be cited as the "New York health act".\n\nSECTION 2. Legislative findings and intent.\nThe legislature finds that all residents of the state have the right to health care. While the federal Affordable Care Act brought many improvements in health care and health coverage, many New Yorkers still lack coverage or have coverage that is inadequate. Millions of New Yorkers do not get the health care they need, and millions more are afraid they will not be able to afford the health care they need in the future. New Yorkers, as individuals, employers, and taxpayers have experienced a rise in the cost of health care and coverage in recent years, including rising premiums, deductibles and co-pays, restricted provider networks and high out-of-network charges. Many commercial health insurance plans severely restrict which health care providers patients may see and what services they may receive.',
  },
  {
    id: "tx-hb1",
    bill_id: 1003,
    number: "HB 1",
    title: "General Appropriations Bill",
    state: "Texas",
    state_id: "tx",
    session_id: 3,
    status: "Passed",
    status_date: "2023-05-29",
    last_action: "Signed by Governor",
    last_action_date: "2023-05-29",
    description:
      "This bill is the state budget for the 2024-2025 biennium. It appropriates money for the support of state government for the fiscal years beginning September 1, 2023 and ending August 31, 2025.",
    sponsors: [{ id: "tx-rep-bonnen", name: "Representative Greg Bonnen", party: "Republican", district: "24" }],
    history: [
      { date: "2023-01-10", action: "Introduced" },
      { date: "2023-02-15", action: "Referred to Appropriations Committee" },
      { date: "2023-03-20", action: "Passed Committee (25-0)" },
      { date: "2023-04-05", action: "Passed House (145-2)" },
      { date: "2023-04-10", action: "Referred to Senate Finance Committee" },
      { date: "2023-04-25", action: "Passed Committee (15-0)" },
      { date: "2023-05-10", action: "Passed Senate (31-0)" },
      { date: "2023-05-15", action: "Conference Committee Report adopted" },
      { date: "2023-05-20", action: "Sent to Governor" },
      { date: "2023-05-29", action: "Signed by Governor" },
    ],
    committees: ["House Committee on Appropriations", "Senate Committee on Finance"],
    full_text:
      "ARTICLE I. GENERAL PROVISIONS\nSECTION 1.01. This Act shall be known as the General Appropriations Act.\n\nSECTION 1.02. The appropriations made in this Act are for the purpose of supporting the functions of state government for the fiscal years beginning September 1, 2023 and ending August 31, 2025.\n\nARTICLE II. EDUCATION\nSECTION 2.01. The following amounts are appropriated from the general revenue fund to the Texas Education Agency for the fiscal years beginning September 1, 2023 and ending August 31, 2025:\n(1) For fiscal year 2024: $25,000,000,000\n(2) For fiscal year 2025: $25,500,000,000",
  },
  {
    id: "fl-sb1",
    bill_id: 1004,
    number: "SB 1",
    title: "Relating to Child Welfare",
    state: "Florida",
    state_id: "fl",
    session_id: 4,
    status: "Introduced",
    status_date: "2023-03-07",
    last_action: "Introduced",
    last_action_date: "2023-03-07",
    description:
      "This bill would make various changes to Florida's child welfare system, including strengthening protections for children in foster care, improving oversight of child welfare agencies, and increasing support for foster parents.",
    sponsors: [{ id: "fl-sen-simon", name: "Senator Corey Simon", party: "Republican", district: "3" }],
    history: [{ date: "2023-03-07", action: "Introduced" }],
    committees: ["Senate Committee on Children, Families, and Elder Affairs", "Senate Committee on Appropriations"],
    full_text:
      'Be It Enacted by the Legislature of the State of Florida:\n\nSection 1. Section 39.01, Florida Statutes, is amended to read:\n39.01 Definitions.—When used in this chapter, unless the context otherwise requires:\n(1) "Abandoned" or "abandonment" means a situation in which the parent or legal custodian of a child or, in the absence of a parent or legal custodian, the caregiver, while being able, makes no provision for the child\'s support and has failed to establish or maintain a substantial and positive relationship with the child. For purposes of this subsection, "establish or maintain a substantial and positive relationship" includes, but is not limited to, frequent and regular contact with the child through frequent and regular visitation or frequent and regular communication to or with the child, and the exercise of parental rights and responsibilities.',
  },
  {
    id: "il-hb1",
    bill_id: 1005,
    number: "HB 1",
    title: "BUDGET IMPLEMENTATION",
    state: "Illinois",
    state_id: "il",
    session_id: 5,
    status: "Passed",
    status_date: "2023-06-01",
    last_action: "Public Act",
    last_action_date: "2023-06-01",
    description:
      "This bill implements the state budget for fiscal year 2024. It makes various changes to state programs and operations to be consistent with the budget.",
    sponsors: [{ id: "il-rep-harris", name: "Representative Harris", party: "Democratic", district: "13" }],
    history: [
      { date: "2023-01-11", action: "Introduced" },
      { date: "2023-02-15", action: "Referred to Executive Committee" },
      { date: "2023-03-20", action: "Passed Committee (9-6)" },
      { date: "2023-04-05", action: "Passed House (73-44)" },
      { date: "2023-04-10", action: "Referred to Senate Assignments Committee" },
      { date: "2023-04-15", action: "Assigned to Senate Executive Committee" },
      { date: "2023-04-25", action: "Passed Committee (11-7)" },
      { date: "2023-05-10", action: "Passed Senate (37-22)" },
      { date: "2023-05-15", action: "Sent to Governor" },
      { date: "2023-06-01", action: "Signed by Governor. Public Act 103-0001." },
    ],
    committees: ["House Executive Committee", "Senate Executive Committee"],
    full_text:
      "AN ACT concerning finance.\n\nBe it enacted by the People of the State of Illinois, represented in the General Assembly:\n\nArticle 1. Short Title; Purpose\n\nSection 1-1. Short title. This Act may be cited as the FY2024 Budget Implementation Act.\n\nSection 1-5. Purpose. It is the purpose of this Act to make changes in State programs that are necessary to implement the State budget for Fiscal Year 2024.",
  },
  {
    id: "pa-hb1",
    bill_id: 1006,
    number: "HB 1",
    title: "An Act providing for competitive integrated employment for individuals with disabilities",
    state: "Pennsylvania",
    state_id: "pa",
    session_id: 6,
    status: "Failed",
    status_date: "2023-06-30",
    last_action: "Laid on the table",
    last_action_date: "2023-06-30",
    description:
      "This bill would promote competitive integrated employment for individuals with disabilities. It would phase out subminimum wage for workers with disabilities and establish a technical assistance program to help employers and workers transition to competitive integrated employment.",
    sponsors: [{ id: "pa-rep-klunk", name: "Representative Klunk", party: "Republican", district: "169" }],
    history: [
      { date: "2023-01-03", action: "Introduced" },
      { date: "2023-01-10", action: "Referred to Labor and Industry Committee" },
      { date: "2023-02-15", action: "Public hearing held" },
      { date: "2023-03-20", action: "Passed Committee (15-10)" },
      { date: "2023-04-05", action: "First consideration" },
      { date: "2023-04-25", action: "Second consideration" },
      { date: "2023-05-10", action: "Third consideration" },
      { date: "2023-05-15", action: "Failed House vote (90-113)" },
      { date: "2023-06-30", action: "Laid on the table" },
    ],
    committees: ["House Labor and Industry Committee"],
    full_text:
      "AN ACT\nProviding for competitive integrated employment for individuals with disabilities.\n\nThe General Assembly of the Commonwealth of Pennsylvania hereby enacts as follows:\n\nSection 1. Short title.\nThis act shall be known and may be cited as the Employment First Act.\n\nSection 2. Declaration of policy.\nIt is the policy of this Commonwealth that competitive integrated employment is the preferred outcome for all individuals with disabilities, regardless of the severity or nature of their disability.",
  },
  {
    id: "ca-ab22",
    bill_id: 1007,
    number: "AB 22",
    title: "Tenant protections: just cause termination: rent caps",
    state: "California",
    state_id: "ca",
    session_id: 1,
    status: "In Committee",
    status_date: "2023-04-26",
    last_action: "In committee: Set, first hearing. Hearing canceled at the request of author.",
    last_action_date: "2023-04-26",
    description:
      "This bill would expand tenant protections in California by strengthening just cause eviction requirements and lowering the allowable annual rent increase cap from 10% to 5% plus the percentage change in the cost of living.",
    sponsors: [{ id: "ca-asm-haney", name: "Assemblymember Matt Haney", party: "Democratic", district: "17" }],
    history: [
      { date: "2022-12-05", action: "Introduced" },
      { date: "2023-01-12", action: "Referred to Committee on Housing and Community Development" },
      { date: "2023-04-26", action: "In committee: Set, first hearing. Hearing canceled at the request of author." },
    ],
    committees: ["Assembly Committee on Housing and Community Development", "Assembly Committee on Judiciary"],
    full_text:
      "SECTION 1. Section 1946.2 of the Civil Code is amended to read:\n1946.2. (a) Notwithstanding any other law, after a tenant has continuously and lawfully occupied a residential real property for 12 months, the owner of the residential real property shall not terminate the tenancy without just cause, which shall be stated in the written notice to terminate tenancy.\n\nSECTION 2. Section 1947.12 of the Civil Code is amended to read:\n1947.12. (a) (1) Subject to subdivision (b), an owner of residential real property shall not, over the course of any 12-month period, increase the gross rental rate for a dwelling or a unit more than 5 percent plus the percentage change in the cost of living, or 10 percent, whichever is lower, of the lowest gross rental rate charged for that dwelling or unit at any time during the 12 months prior to the effective date of the increase.",
  },
  {
    id: "ny-s222",
    bill_id: 1008,
    number: "S 222",
    title:
      "Relates to prohibiting landlords from declining to rent or lease a residential unit to a potential tenant on the sole basis that the potential tenant was previously involved in a landlord-tenant action",
    state: "New York",
    state_id: "ny",
    session_id: 2,
    status: "Introduced",
    status_date: "2023-01-04",
    last_action: "Referred to Judiciary",
    last_action_date: "2023-01-04",
    description:
      "This bill would prohibit landlords from refusing to rent to potential tenants solely because they were previously involved in a landlord-tenant legal action. It aims to prevent discrimination against tenants who have exercised their legal rights in housing court.",
    sponsors: [{ id: "ny-sen-hoylman", name: "Senator Brad Hoylman-Sigal", party: "Democratic", district: "47" }],
    history: [
      { date: "2023-01-04", action: "Introduced" },
      { date: "2023-01-04", action: "Referred to Judiciary" },
    ],
    committees: [
      "Senate Committee on Judiciary",
      "Senate Committee on Housing, Construction and Community Development",
    ],
    full_text:
      "SECTION 1. The real property law is amended by adding a new section 227-g to read as follows:\n§ 227-g. Prohibition against refusing to rent or lease based on landlord-tenant actions. 1. No landlord shall refuse to rent or lease a residential unit to a potential tenant on the sole basis that the potential tenant was previously involved in a landlord-tenant action or summary proceeding under article seven of the real property actions and proceedings law.\n\n2. Any person who violates the provisions of this section shall be liable for actual damages, and punitive damages not to exceed the greater of one thousand dollars or the actual damages sustained by the potential tenant, and reasonable attorney's fees.",
  },
]
