// Mock representatives data

export const representatives = [
  {
    id: "ca-sen-wiener",
    name: "Scott Wiener",
    state: "California",
    state_id: "ca",
    district: "11",
    party: "Democratic",
    active: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Scott Wiener is a California State Senator representing District 11, which includes San Francisco and parts of San Mateo County. He chairs the Housing Committee and focuses on housing, transportation, civil rights, criminal justice reform, and environmental issues. Before being elected to the Senate in 2016, Wiener served as a member of the San Francisco Board of Supervisors, representing District 8. He is known for his work on housing legislation, including SB 35, which streamlines housing approvals in cities that have fallen behind on their housing goals.",
    committees: [
      "Chair, Housing Committee",
      "Member, Environmental Quality Committee",
      "Member, Judiciary Committee",
      "Member, Transportation Committee",
      "Member, Public Safety Committee",
    ],
    contact: {
      email: "senator.wiener@senate.ca.gov",
      phone: "(415) 557-1300",
      office: "State Capitol, Room 5100, Sacramento, CA 95814",
    },
    sponsoredBills: [
      {
        id: "ca-sb1",
        number: "SB 1",
        title: "California Environmental Quality Act: housing and land use",
        state: "California",
        status: "Passed",
        lastAction: "Signed by Governor",
        lastActionDate: "2023-10-10",
        sponsors: ["Senator Scott Wiener"],
      },
      {
        id: "ca-sb10",
        number: "SB 10",
        title: "Planning and zoning: housing development: density",
        state: "California",
        status: "Passed",
        lastAction: "Signed by Governor",
        lastActionDate: "2021-09-16",
        sponsors: ["Senator Scott Wiener"],
      },
      {
        id: "ca-sb35",
        number: "SB 35",
        title: "Planning and zoning: affordable housing: streamlined approval process",
        state: "California",
        status: "Passed",
        lastAction: "Signed by Governor",
        lastActionDate: "2017-09-29",
        sponsors: ["Senator Scott Wiener"],
      },
    ],
  },
  {
    id: "ny-asm-gottfried",
    name: "Richard Gottfried",
    state: "New York",
    state_id: "ny",
    district: "75",
    party: "Democratic",
    active: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Richard Gottfried represented the 75th Assembly District in Manhattan, which includes Chelsea, Hell's Kitchen, Murray Hill, and parts of Midtown. He served as Chair of the Assembly Health Committee from 1987 until his retirement in 2022, making him the longest-serving chair of the committee in New York history. Throughout his career, he was a leading advocate for progressive health care reform, including the New York Health Act, which would establish a single-payer health care system in New York.",
    committees: [
      "Chair, Health Committee (former)",
      "Member, Judiciary Committee (former)",
      "Member, Higher Education Committee (former)",
    ],
    contact: {
      email: "gottfriedr@nyassembly.gov",
      phone: "(212) 807-7900",
      office: "214 West 29th Street, Suite 1002, New York, NY 10001",
    },
    sponsoredBills: [
      {
        id: "ny-a1",
        number: "A 1",
        title: "Relates to establishing the New York health act and to making appropriations therefor",
        state: "New York",
        status: "In Committee",
        lastAction: "Referred to Health Committee",
        lastActionDate: "2023-01-04",
        sponsors: ["Assemblymember Richard Gottfried", "Assemblymember Jessica González-Rojas"],
      },
    ],
  },
  {
    id: "tx-rep-bonnen",
    name: "Greg Bonnen",
    state: "Texas",
    state_id: "tx",
    district: "24",
    party: "Republican",
    active: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Dr. Greg Bonnen represents District 24 in the Texas House of Representatives, which includes parts of Galveston County. He serves as the Chair of the House Appropriations Committee, which is responsible for the state budget. Dr. Bonnen is a neurosurgeon by profession and brings his medical expertise to his work in the legislature, particularly on health care policy issues.",
    committees: [
      "Chair, Appropriations Committee",
      "Member, Public Health Committee",
      "Member, Legislative Budget Board",
    ],
    contact: {
      email: "greg.bonnen@house.texas.gov",
      phone: "(512) 463-0729",
      office: "P.O. Box 2910, Austin, TX 78768",
    },
    sponsoredBills: [
      {
        id: "tx-hb1",
        number: "HB 1",
        title: "General Appropriations Bill",
        state: "Texas",
        status: "Passed",
        lastAction: "Signed by Governor",
        lastActionDate: "2023-05-29",
        sponsors: ["Representative Greg Bonnen"],
      },
    ],
  },
  {
    id: "fl-sen-simon",
    name: "Corey Simon",
    state: "Florida",
    state_id: "fl",
    district: "3",
    party: "Republican",
    active: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Corey Simon represents District 3 in the Florida Senate, which includes several counties in the Florida Panhandle. Before entering politics, Simon was a professional football player who played in the NFL for eight seasons, including with the Philadelphia Eagles and Indianapolis Colts. He also served as the CEO of Volunteer Florida before being elected to the Senate in 2022.",
    committees: [
      "Chair, Education Committee",
      "Member, Children, Families, and Elder Affairs Committee",
      "Member, Appropriations Committee on Education",
      "Member, Military and Veterans Affairs, Space, and Domestic Security Committee",
    ],
    contact: {
      email: "simon.corey@flsenate.gov",
      phone: "(850) 487-5003",
      office: "302 Senate Building, 404 South Monroe Street, Tallahassee, FL 32399-1100",
    },
    sponsoredBills: [
      {
        id: "fl-sb1",
        number: "SB 1",
        title: "Relating to Child Welfare",
        state: "Florida",
        status: "Introduced",
        lastAction: "Introduced",
        lastActionDate: "2023-03-07",
        sponsors: ["Senator Corey Simon"],
      },
    ],
  },
  {
    id: "il-rep-harris",
    name: "Gregory Harris",
    state: "Illinois",
    state_id: "il",
    district: "13",
    party: "Democratic",
    active: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Gregory Harris represented the 13th District in the Illinois House of Representatives from 2006 to 2023. He served as the House Majority Leader from 2019 to 2023 and was the first openly gay person to serve in leadership in the Illinois General Assembly. Throughout his career, he was a champion for health care access, LGBTQ+ rights, and social services.",
    committees: [
      "Former House Majority Leader",
      "Former Chair, Appropriations-Human Services Committee",
      "Former Member, Human Services Committee",
    ],
    contact: {
      email: "greg@gregharris.org",
      phone: "(773) 348-3434",
      office: "1967 W. Montrose Ave., Chicago, IL 60613",
    },
    sponsoredBills: [
      {
        id: "il-hb1",
        number: "HB 1",
        title: "BUDGET IMPLEMENTATION",
        state: "Illinois",
        status: "Passed",
        lastAction: "Public Act",
        lastActionDate: "2023-06-01",
        sponsors: ["Representative Harris"],
      },
    ],
  },
  {
    id: "pa-rep-klunk",
    name: "Kate Klunk",
    state: "Pennsylvania",
    state_id: "pa",
    district: "169",
    party: "Republican",
    active: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Kate Klunk represents the 169th Legislative District in the Pennsylvania House of Representatives, which includes parts of York County. She serves on several committees, including the Labor and Industry Committee and the Children and Youth Committee. Before being elected to the House, Klunk worked as an attorney and served as a staff member in the White House under President George W. Bush.",
    committees: [
      "Member, Labor and Industry Committee",
      "Member, Children and Youth Committee",
      "Member, Commerce Committee",
      "Member, Gaming Oversight Committee",
    ],
    contact: {
      email: "kklunk@pahousegop.com",
      phone: "(717) 630-8942",
      office: "118 Carlisle Street, Suite 300, Hanover, PA 17331",
    },
    sponsoredBills: [
      {
        id: "pa-hb1",
        number: "HB 1",
        title: "An Act providing for competitive integrated employment for individuals with disabilities",
        state: "Pennsylvania",
        status: "Failed",
        lastAction: "Laid on the table",
        lastActionDate: "2023-06-30",
        sponsors: ["Representative Klunk"],
      },
    ],
  },
  {
    id: "ca-asm-haney",
    name: "Matt Haney",
    state: "California",
    state_id: "ca",
    district: "17",
    party: "Democratic",
    active: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Matt Haney represents the 17th Assembly District in the California State Assembly, which includes eastern San Francisco. Before being elected to the Assembly in 2022, Haney served on the San Francisco Board of Supervisors, representing District 6. He has focused on housing, homelessness, public safety, and environmental issues throughout his political career.",
    committees: [
      "Chair, Housing and Community Development Committee",
      "Member, Budget Committee",
      "Member, Public Safety Committee",
      "Member, Environmental Safety and Toxic Materials Committee",
    ],
    contact: {
      email: "assemblymember.haney@assembly.ca.gov",
      phone: "(415) 557-3013",
      office: "455 Golden Gate Avenue, Suite 14300, San Francisco, CA 94102",
    },
    sponsoredBills: [
      {
        id: "ca-ab22",
        number: "AB 22",
        title: "Tenant protections: just cause termination: rent caps",
        state: "California",
        status: "In Committee",
        lastAction: "In committee: Set, first hearing. Hearing canceled at the request of author.",
        lastActionDate: "2023-04-26",
        sponsors: ["Assemblymember Matt Haney"],
      },
    ],
  },
  {
    id: "ny-sen-hoylman",
    name: "Brad Hoylman-Sigal",
    state: "New York",
    state_id: "ny",
    district: "47",
    party: "Democratic",
    active: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    bio: "Brad Hoylman-Sigal represents the 47th District in the New York State Senate, which includes parts of Manhattan. He serves as the Chair of the Judiciary Committee and has been a leading advocate for LGBTQ+ rights, environmental protection, and tenant protections. Before being elected to the Senate, Hoylman-Sigal was a community board chair and an attorney.",
    committees: [
      "Chair, Judiciary Committee",
      "Member, Environmental Conservation Committee",
      "Member, Housing, Construction and Community Development Committee",
      "Member, Health Committee",
      "Member, Rules Committee",
    ],
    contact: {
      email: "hoylman@nysenate.gov",
      phone: "(212) 633-8052",
      office: "322 Eighth Avenue, Suite 1700, New York, NY 10001",
    },
    sponsoredBills: [
      {
        id: "ny-s222",
        number: "S 222",
        title:
          "Relates to prohibiting landlords from declining to rent or lease a residential unit to a potential tenant on the sole basis that the potential tenant was previously involved in a landlord-tenant action",
        state: "New York",
        status: "Introduced",
        lastAction: "Referred to Judiciary",
        lastActionDate: "2023-01-04",
        sponsors: ["Senator Brad Hoylman-Sigal"],
      },
    ],
  },
]
